// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
// ReSharper disable VirtualMemberCallInConstructor
namespace CategoriesProductsLibrary.models;

public partial class Categories
{
    public Categories()
    {
        Products = new HashSet<Products>();
    }

    public int CategoryId { get; set; }
    public string CategoryName { get; set; }

    public virtual ICollection<Products> Products { get; set; }
}