// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EmployeesWithRelationsLibrary.Models
{
    public partial class Employees
    {
        public Employees()
        {
            InverseReportsToNavigationEmployee = new HashSet<Employees>();
        }

        public int EmployeeID { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public int? ContactTypeIdentifier { get; set; }
        public string TitleOfCourtesy { get; set; }
        public DateTime? BirthDate { get; set; }
        public int? CountryIdentifier { get; set; }
        public int? ReportsToNavigationEmployeeID { get; set; }

        public virtual ContactType ContactTypeIdentifierNavigation { get; set; }
        public virtual Countries CountryIdentifierNavigation { get; set; }
        public virtual Employees ReportsToNavigationEmployee { get; set; }
        public virtual ICollection<Employees> InverseReportsToNavigationEmployee { get; set; }
    }
}