// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using HasDataConsoleApp.Data.Configurations;
using HasDataConsoleApp.Models;
using Microsoft.EntityFrameworkCore;
using Bogus;
using ConfigurationLibrary.Classes;

#nullable disable

#nullable disable

namespace HasDataConsoleApp.Data;

public partial class Context : DbContext
{
    public Context()
    {
    }

    public Context(DbContextOptions<Context> options)
        : base(options)
    {
    }

    public virtual DbSet<Product> Product { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        if (!optionsBuilder.IsConfigured)
        {
            optionsBuilder.UseSqlServer(ConfigurationHelper.ConnectionString());
        }
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS");

        modelBuilder.ApplyConfiguration(new ProductConfiguration());

        // seed for primary key
        var identifier = 1;

        // setup to create data
        Faker<Product> products = new Faker<Product>()
            .RuleFor(p => p.Id, f => identifier++)
            .RuleFor(p => p.ProductName, f => f.Commerce.ProductName())
            .RuleFor(p => p.Category, f => f.Commerce.Categories(1).First())
            .RuleFor(p => p.Price, f => f.Commerce.Price(1).First());

        modelBuilder
            .Entity<Product>()
            // generate data
            .HasData(products.GenerateBetween(10, 10));

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}