
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using HasDataConsoleApp.Data;
using HasDataConsoleApp.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;
using Bogus;

namespace HasDataConsoleApp.Data.Configurations
{
    public partial class ProductConfiguration : IEntityTypeConfiguration<Product>
    {
        public void Configure(EntityTypeBuilder<Product> entity)
        {
            entity.Property(e => e.Price).HasColumnType("decimal(18, 0)");


            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Product> entity);
    }
}
